dist: trusty
sudo: false
language: go
go:
- 1.12.6

before_install:
  - mkdir -p $HOME/gopath/src/github.com/terraform-providers/terraform-provider-avi
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/terraform-providers/terraform-provider-avi
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/terraform-providers/terraform-provider-avi
  - cd $HOME/gopath/src/github.com/terraform-providers/terraform-provider-avi

env: GOPROXY="https://proxy.golang.org" 
install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh
- go get github.com/hashicorp/terraform
- go get github.com/kardianos/govendor
- go get github.com/avinetworks/sdk/go/clients
- go get github.com/avinetworks/sdk/go/session

script:
- make
- make test

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip

notifications:
  email:
    recipients:
      - rohan.suryawanshi@avinetworks.com
    on_failure: always
